### ISSUE TITLE
[question] difference betwen vishop and vim-upload

### ISSUE THREAD

**Issue by Freed-Wu** [Xvezda/vishop#10]
Any big difference between this program with [vim-upload](https://metacpan.org/pod/VIM::Uploader) which prove its advantage? TIA!

**Comment by Xvezda** [comment]
@Freed-Wu 
I haven't use vim-upload before
but based on the link provided, I would say the big differences are:
| vishop | vim-upload |
|--------|------------|
| python | perl |
| has metadata file (vishop.json) | x |
| has extra builtin zip/tar archive features and upload right away | just for uploading |
| supports user info lookup (via info command) | x |

**Comment by Freed-Wu** [comment]
Thanks!
